# Generated by Django 4.1.7 on 2023-03-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdp_data',
            name='date',
        ),
        migrations.AddField(
            model_name='gdp_data',
            name='year',
            field=models.IntegerField(default=None),
        ),
    ]
