# Generated by Django 4.1.7 on 2023-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_remove_gdp_data_date_gdp_data_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usd_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
    ]
